"""initial compliance schema

Revision ID: a56b231c5b58
Revises: 0001
Create Date: 2026-09-14 00:09:37.389316
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


revision: str = 'a56b231c5b58'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lease_holders',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.Enum('company', 'individual', 'cooperative', 'joint_venture', 'government_undertaking', name='holderentitytype', native_enum=False, length=48), server_default=sa.text("'company'"), nullable=False),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('tax_identifier', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address_line', sa.String(length=300), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), server_default=sa.text("'India'"), nullable=False),
    sa.Column('is_operator', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lease_holders')),
    sa.UniqueConstraint('registration_number', name=op.f('uq_lease_holders_registration_number'))
    )
    op.create_index(op.f('ix_lease_holders_name'), 'lease_holders', ['name'], unique=False)
    op.create_index(op.f('ix_lease_holders_tax_identifier'), 'lease_holders', ['tax_identifier'], unique=False)
    op.create_table('minerals',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('major', 'minor', name='mineralcategory', native_enum=False, length=48), nullable=False),
    sa.Column('royalty_basis', sa.Enum('ad_valorem', 'specific', 'exempt', name='royaltybasis', native_enum=False, length=48), nullable=False),
    sa.Column('royalty_rate', sa.Numeric(precision=12, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('royalty_unit', sa.String(length=48), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_minerals'))
    )
    op.create_index(op.f('ix_minerals_category'), 'minerals', ['category'], unique=False)
    op.create_index(op.f('ix_minerals_code'), 'minerals', ['code'], unique=True)
    op.create_index(op.f('ix_minerals_name'), 'minerals', ['name'], unique=False)
    op.create_table('obligations',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('return_filing', 'payment', 'inspection', 'safety', 'environment', 'social', 'reporting', name='obligationcategory', native_enum=False, length=48), nullable=False),
    sa.Column('legal_reference', sa.String(length=200), nullable=True),
    sa.Column('jurisdiction', sa.String(length=120), nullable=True),
    sa.Column('recurrence', sa.Enum('one_time', 'monthly', 'quarterly', 'half_yearly', 'annual', name='recurrence', native_enum=False, length=48), nullable=False),
    sa.Column('due_days_after_period_end', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('grace_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('fiscal_year_end_month', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('applies_to_lease_types', sa.ARRAY(sa.String(length=48)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('applies_to_mineral_categories', sa.ARRAY(sa.String(length=48)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('requires_payment', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('penalty_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligations'))
    )
    op.create_index(op.f('ix_obligations_category'), 'obligations', ['category'], unique=False)
    op.create_index(op.f('ix_obligations_code'), 'obligations', ['code'], unique=True)
    op.create_index(op.f('ix_obligations_jurisdiction'), 'obligations', ['jurisdiction'], unique=False)
    op.create_table('leases',
    sa.Column('lease_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lease_type', sa.Enum('prospecting_licence', 'mining_lease', 'quarry_lease', 'composite_licence', name='leasetype', native_enum=False, length=48), server_default=sa.text("'mining_lease'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'pending_renewal', 'suspended', 'expired', 'surrendered', 'revoked', name='leasestatus', native_enum=False, length=48), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('holder_id', sa.UUID(), nullable=False),
    sa.Column('mineral_id', sa.UUID(), nullable=False),
    sa.Column('area_hectares', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('village', sa.String(length=160), nullable=True),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=80), server_default=sa.text("'India'"), nullable=False),
    # spatial_index=False here, with the GIST indexes created explicitly below.
    # GeoAlchemy2 also creates a spatial index implicitly during create_table, so
    # leaving it on produced a duplicate 'idx_leases_boundary' and aborted the run.
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', spatial_index=False), nullable=True),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('royalty_basis', sa.Enum('ad_valorem', 'specific', 'exempt', name='royaltybasis', native_enum=False, length=48), nullable=True),
    sa.Column('royalty_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('royalty_unit', sa.String(length=48), nullable=True),
    sa.Column('annual_production_tonnes', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holder_id'], ['lease_holders.id'], name=op.f('fk_leases_holder_id_lease_holders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mineral_id'], ['minerals.id'], name=op.f('fk_leases_mineral_id_minerals'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leases'))
    )
    op.create_index('idx_leases_boundary', 'leases', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index('idx_leases_centroid', 'leases', ['centroid'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_leases_district'), 'leases', ['district'], unique=False)
    op.create_index(op.f('ix_leases_effective_from'), 'leases', ['effective_from'], unique=False)
    op.create_index(op.f('ix_leases_effective_to'), 'leases', ['effective_to'], unique=False)
    op.create_index('ix_leases_effective_to_status', 'leases', ['effective_to', 'status'], unique=False)
    op.create_index(op.f('ix_leases_holder_id'), 'leases', ['holder_id'], unique=False)
    op.create_index(op.f('ix_leases_lease_number'), 'leases', ['lease_number'], unique=True)
    op.create_index(op.f('ix_leases_lease_type'), 'leases', ['lease_type'], unique=False)
    op.create_index(op.f('ix_leases_mineral_id'), 'leases', ['mineral_id'], unique=False)
    op.create_index(op.f('ix_leases_name'), 'leases', ['name'], unique=False)
    op.create_index(op.f('ix_leases_state'), 'leases', ['state'], unique=False)
    op.create_index(op.f('ix_leases_status'), 'leases', ['status'], unique=False)
    op.create_table('lease_obligations',
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'submitted', 'overdue', 'waived', 'not_applicable', name='obligationstatus', native_enum=False, length=48), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('evidence_path', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('waiver_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], name=op.f('fk_lease_obligations_lease_id_leases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], name=op.f('fk_lease_obligations_obligation_id_obligations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lease_obligations'))
    )
    op.create_index(op.f('ix_lease_obligations_due_date'), 'lease_obligations', ['due_date'], unique=False)
    op.create_index('ix_lease_obligations_due_status', 'lease_obligations', ['due_date', 'status'], unique=False)
    op.create_index(op.f('ix_lease_obligations_lease_id'), 'lease_obligations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_lease_obligations_obligation_id'), 'lease_obligations', ['obligation_id'], unique=False)
    op.create_index(op.f('ix_lease_obligations_period_end'), 'lease_obligations', ['period_end'], unique=False)
    op.create_index(op.f('ix_lease_obligations_status'), 'lease_obligations', ['status'], unique=False)
    op.create_index('uq_lease_obligations_lease_obligation_period', 'lease_obligations', ['lease_id', 'obligation_id', sa.literal_column("COALESCE(period_start, DATE '0001-01-01')")], unique=True)
    op.create_table('licences',
    sa.Column('lease_id', sa.UUID(), nullable=False),
    sa.Column('licence_type', sa.Enum('environmental_clearance', 'forest_clearance', 'consent_to_operate', 'mining_plan_approval', 'ground_water_ntoc', 'explosive_licence', 'drone_survey_approval', 'lease_deed', name='licencetype', native_enum=False, length=48), nullable=False),
    sa.Column('status', sa.Enum('pending', 'valid', 'expiring_soon', 'expired', 'revoked', name='licencestatus', native_enum=False, length=48), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('authority', sa.String(length=160), nullable=False),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('document_path', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], name=op.f('fk_licences_lease_id_leases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licences')),
    sa.UniqueConstraint('lease_id', 'licence_type', 'reference_number', name=op.f('uq_licences_lease_id_licence_type_reference_number'))
    )
    op.create_index(op.f('ix_licences_authority'), 'licences', ['authority'], unique=False)
    op.create_index(op.f('ix_licences_lease_id'), 'licences', ['lease_id'], unique=False)
    op.create_index(op.f('ix_licences_licence_type'), 'licences', ['licence_type'], unique=False)
    op.create_index(op.f('ix_licences_reference_number'), 'licences', ['reference_number'], unique=False)
    op.create_index(op.f('ix_licences_status'), 'licences', ['status'], unique=False)
    op.create_index(op.f('ix_licences_valid_to'), 'licences', ['valid_to'], unique=False)
    op.create_index('ix_licences_valid_to_status', 'licences', ['valid_to', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_licences_valid_to_status', table_name='licences')
    op.drop_index(op.f('ix_licences_valid_to'), table_name='licences')
    op.drop_index(op.f('ix_licences_status'), table_name='licences')
    op.drop_index(op.f('ix_licences_reference_number'), table_name='licences')
    op.drop_index(op.f('ix_licences_licence_type'), table_name='licences')
    op.drop_index(op.f('ix_licences_lease_id'), table_name='licences')
    op.drop_index(op.f('ix_licences_authority'), table_name='licences')
    op.drop_table('licences')
    op.drop_index('uq_lease_obligations_lease_obligation_period', table_name='lease_obligations')
    op.drop_index(op.f('ix_lease_obligations_status'), table_name='lease_obligations')
    op.drop_index(op.f('ix_lease_obligations_period_end'), table_name='lease_obligations')
    op.drop_index(op.f('ix_lease_obligations_obligation_id'), table_name='lease_obligations')
    op.drop_index(op.f('ix_lease_obligations_lease_id'), table_name='lease_obligations')
    op.drop_index('ix_lease_obligations_due_status', table_name='lease_obligations')
    op.drop_index(op.f('ix_lease_obligations_due_date'), table_name='lease_obligations')
    op.drop_table('lease_obligations')
    op.drop_index(op.f('ix_leases_status'), table_name='leases')
    op.drop_index(op.f('ix_leases_state'), table_name='leases')
    op.drop_index(op.f('ix_leases_name'), table_name='leases')
    op.drop_index(op.f('ix_leases_mineral_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_lease_type'), table_name='leases')
    op.drop_index(op.f('ix_leases_lease_number'), table_name='leases')
    op.drop_index(op.f('ix_leases_holder_id'), table_name='leases')
    op.drop_index('ix_leases_effective_to_status', table_name='leases')
    op.drop_index(op.f('ix_leases_effective_to'), table_name='leases')
    op.drop_index(op.f('ix_leases_effective_from'), table_name='leases')
    op.drop_index(op.f('ix_leases_district'), table_name='leases')
    op.drop_index('idx_leases_centroid', table_name='leases', postgresql_using='gist')
    op.drop_index('idx_leases_boundary', table_name='leases', postgresql_using='gist')
    op.drop_table('leases')
    op.drop_index(op.f('ix_obligations_jurisdiction'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_code'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_category'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_minerals_name'), table_name='minerals')
    op.drop_index(op.f('ix_minerals_code'), table_name='minerals')
    op.drop_index(op.f('ix_minerals_category'), table_name='minerals')
    op.drop_table('minerals')
    op.drop_index(op.f('ix_lease_holders_tax_identifier'), table_name='lease_holders')
    op.drop_index(op.f('ix_lease_holders_name'), table_name='lease_holders')
    op.drop_table('lease_holders')
    # ### end Alembic commands ###
