"""identity and audit trail

Revision ID: 349db90d53f4
Revises: a56b231c5b58
Create Date: 2026-09-14 01:19:01.236451
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

revision: str = '349db90d53f4'
down_revision: Union[str, None] = 'a56b231c5b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=False),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('actor_label', sa.String(length=200), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=True),
    sa.Column('auth_method', sa.String(length=24), nullable=False),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'submit', 'waive', 'reopen', 'generate', 'refresh', 'login', 'access_denied', name='auditaction', native_enum=False, length=48), nullable=False),
    sa.Column('outcome', sa.Enum('succeeded', 'denied', 'failed', name='auditoutcome', native_enum=False, length=48), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('lease', 'licence', 'obligation_rule', 'calendar_entry', 'mineral', 'holder', 'user', 'session', name='auditentity', native_enum=False, length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('entity_label', sa.String(length=240), nullable=True),
    sa.Column('changed_fields', sa.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('http_path', sa.String(length=400), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index('ix_audit_log_actor_time', 'audit_log', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_outcome'), 'audit_log', ['outcome'], unique=False)
    op.create_index('ix_audit_log_outcome_time', 'audit_log', ['outcome', 'occurred_at'], unique=False)
    op.create_table('app_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('admin', 'inspector', 'operator', name='approle', native_enum=False, length=48), server_default=sa.text("'operator'"), nullable=False),
    sa.Column('holder_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['holder_id'], ['lease_holders.id'], name=op.f('fk_app_users_holder_id_lease_holders'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_users'))
    )
    op.create_index(op.f('ix_app_users_email'), 'app_users', ['email'], unique=False)
    op.create_index(op.f('ix_app_users_holder_id'), 'app_users', ['holder_id'], unique=False)
    op.create_index(op.f('ix_app_users_role'), 'app_users', ['role'], unique=False)
    op.drop_index(op.f('uq_lease_obligations_lease_obligation_period'), table_name='lease_obligations')
    op.create_index('uq_lease_obligations_lease_obligation_period', 'lease_obligations', ['lease_id', 'obligation_id', sa.literal_column("COALESCE(period_start, DATE '0001-01-01')")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lease_obligations_lease_obligation_period', table_name='lease_obligations')
    op.create_index(op.f('uq_lease_obligations_lease_obligation_period'), 'lease_obligations', ['lease_id', 'obligation_id', sa.literal_column("COALESCE(period_start, '0001-01-01'::date)")], unique=True)
    op.drop_index(op.f('ix_app_users_role'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_holder_id'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_email'), table_name='app_users')
    op.drop_table('app_users')
    op.drop_index('ix_audit_log_outcome_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_outcome'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_time', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
